organics ver2

fusion dataset 구성을 위해 파일 수정


pathology : low data 기준 -> 수정
healthy : phrase 기준. 그대로 두기.

In [3]:
import time
import pandas as pd
import re
import shutil
import os
import openpyxl
from glob import glob

In [4]:
DF = pd.read_excel("../only_organics_healthy_available.xlsx")

In [6]:
DF

,RECORDING,PATHOLOGY,DATE,SPEAKER,GENDER,AGE,DETAIL,DIAG
0,715,p,20.05.1998,1407,w,63,Laryngitis; Leukoplakie,structural
1,1303,p,21.04.1999,1407,w,64,Leukoplakie,structural
2,1557,p,08.12.1999,1407,w,65,Leukoplakie,structural
3,1559,p,15.12.1999,1407,w,65,Leukoplakie,structural
4,1864,p,29.11.2000,1407,w,66,Leukoplakie,structural
...,...,...,...,...,...,...,...,...
1226,80,n,13/01/1998,83,w,49,control,control
1227,81,n,13/01/1998,84,m,42,control,control
1228,82,n,13/01/1998,87,w,49,control,control
1229,83,n,13/01/1998,88,w,46,control,control
1230,153,n,11.02.1998,1332,w,60,control,control

In [13]:
a_low = glob("../voice_data/organics_ver2/pathology/a/low/export/*.wav")

In [14]:
len(a_low)

596

In [23]:
recording=[ int(data.split("\\")[1].split("-")[0]) for data in a_low ]

In [27]:
DF_NORMAL = DF[DF['PATHOLOGY']=='n']

In [28]:
DF_PATHOLOGY = DF[DF['RECORDING'].isin(recording)]

In [30]:
DF_NORMAL

      RECORDING PATHOLOGY        DATE  SPEAKER GENDER  AGE   DETAIL     DIAG
597           1         n  20/11/1997        1      w   20  control  control
598           2         n  20/11/1997        2      w   22  control  control
599           3         n  20/11/1997        3      w   23  control  control
600           4         n  20/11/1997        4      m   22  control  control
601           5         n  20/11/1997        5      m   22  control  control
...         ...       ...         ...      ...    ...  ...      ...      ...
1226         80         n  13/01/1998       83      w   49  control  control
1227         81         n  13/01/1998       84      m   42  control  control
1228         82         n  13/01/1998       87      w   49  control  control
1229         83         n  13/01/1998       88      w   46  control  control
1230        153         n  11.02.1998     1332      w   60  control  control

[634 rows x 8 columns]

In [33]:
DF_VER2=pd.concat([DF_PATHOLOGY,DF_NORMAL],axis=0)

In [35]:
DF_VER2.to_excel("../only_organics_healthy_available_ver2.xlsx",index=False)